### ISSUE TITLE
Detect whether code was loaded

### ISSUE THREAD

**Issue by kal27** [tiagohm/CodeView#2]
How could I detect whether the code was loaded? I am trying to open large files and it takes couple seconds to load the code and display it in the layout.
Is there a way I could detect when the code has been displayed so I can display/hide a progressbar?

Thanks

**Comment by kal27** [comment]
Thank you for trying to fix the issue in the latest release but unfortunately it's still not working,

In the console I can see
 I/chromium: [INFO:CONSOLE(2)] "android.onStartCodeHighlight is not a function", source: file:///android_asset/highlightjs/highlight.js (2)
I/chromium: [INFO:CONSOLE(2)] "android.onFinishCodeHighlight is not a function", source: file:///android_asset/highlightjs/highlight.js (2)

If this helps

**Comment by tiagohm** [comment]
Check if you have added the @JavascriptInterface annotation in in the methods in OnHighlightListener implementation

**Comment by kal27** [comment]
Oh Okay fixed it.
The problem is I tried to call 
progressBar.setVisibility(View.VISIBLE); from the OnFinishCodeHighlight method which did not work because the call wasn't made on the UI thread.
What worked is putting the call on the UI thread like this:
                progressBar.post(new Runnable() {
                    @Override
                    public void run() {
                        progressBar.setVisibility(View.VISIBLE);
                    }
                });
